<center><h1><strong>taudata Analytics</strong></h1></center>
<center><h2><strong><font color="blue">DL 02 - Pendahuluan PyTorch untuk Deep learning</font></strong></h2></center>
<img alt="" src="images/covers/taudata-cover.jpg"/>

<b><center>(C) Taufik Sutanto</center>
<center><h3><font color="blue">https://taudataid.github.io/dl02/</font></h3></center>
<center><h3><font color="blue">Video Penjelasan: </font></h3></center>

# <center><font color="blue"> Prasyarat Module </font></center>

### Sebelum dilanjutkan, yakinkan sudah mempelajari dengan baik module:
* https://taudataid.github.io/adsp01/
* https://taudataid.github.io/adsp02/

# <center><font color="blue"> Instalasi </font></center>

* Sangat mudah, ikuti perintah di https://pytorch.org/get-started/locally/
* Perhatikan harware yang dimiliki.
* Saat ini AMD (Rocm) sudah disupport oleh PyTorch dan TensorFlow
* Perhatikan jika anda install PyTorch dan Tensorflow pada environment yang sama.

In [2]:
# Load Module
import torch
import numpy as np

In [3]:
# Kalau saya sukanya cek versi dan apakah PyTorch (atau tensorflow) sudah dapat mengakses GPU atau belum

print("Using Numpy and Pytorch versions = {}, {}".format(np.__version__, torch.__version__))
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device, end=', ')
if device.type == 'cuda': #Additional Info when using cuda
    print(torch.cuda.get_device_name(0))
    print('Currently Memory Allocated, Cached =', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB, ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using Numpy and Pytorch versions = 1.21.5, 1.11.0+cu113
Using device: cuda, NVIDIA GeForce RTX 3060 Laptop GPU
Currently Memory Allocated, Cached = 0.0 GB,  0.0 GB


In [4]:
# Tensor dari Python List

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
x_data.shape, x_data.type()

(torch.Size([2, 2]), 'torch.LongTensor')

In [5]:
# Tensor dari Numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
# Ukuran  & property (shape, datatype) sama, tapi element berbeda.
#  unless explicitly overridden.

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8822, 0.1105],
        [0.7793, 0.3140]]) 



In [10]:
x_ones.shape, x_ones.type()

(torch.Size([2, 2]), 'torch.LongTensor')

In [12]:
# dimensi Tensor adalah Tuple

shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0461, 0.0025, 0.3966],
        [0.4182, 0.3375, 0.1969]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# Check Tensor ada dimana
tensor = torch.rand(3, 4)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [14]:
# Bisa pindah ke GPU ... perhatikan kita bisa punya >1 GPU, index GPU mulai dari 0
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [16]:
# Slicing Tensor = Numpy
tensor = torch.ones(4, 4)
tensor[:,1] = 0.0
tensor[1,:] = -2.0
tensor[-1,-1] = 99.0
print(tensor)

tensor([[ 1.,  0.,  1.,  1.],
        [-2., -2., -2., -2.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1., 99.]])


In [17]:
# Operasi Concatenasi (dan operasi lainnya) juga mirip dengan Numpy

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.],
        [-2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.],
        [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.],
        [ 1.,  0.,  1., 99.,  1.,  0.,  1., 99.,  1.,  0.,  1., 99.]])


In [19]:
# Operasi Tensor = Numpy, berarti element Wise ... Hati-hati tidak seperti Matlab.
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00],
        [4.0000e+00, 4.0000e+00, 4.0000e+00, 4.0000e+00],
        [1.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 0.0000e+00, 1.0000e+00, 9.8010e+03]]) 

tensor * tensor 
 tensor([[1.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00],
        [4.0000e+00, 4.0000e+00, 4.0000e+00, 4.0000e+00],
        [1.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 0.0000e+00, 1.0000e+00, 9.8010e+03]])


In [20]:
# Perkalian Matrix

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[ 3.0000e+00, -6.0000e+00,  3.0000e+00,  1.0100e+02],
        [-6.0000e+00,  1.6000e+01, -6.0000e+00, -2.0200e+02],
        [ 3.0000e+00, -6.0000e+00,  3.0000e+00,  1.0100e+02],
        [ 1.0100e+02, -2.0200e+02,  1.0100e+02,  9.8030e+03]]) 

tensor @ tensor.T 
 tensor([[ 3.0000e+00, -6.0000e+00,  3.0000e+00,  1.0100e+02],
        [-6.0000e+00,  1.6000e+01, -6.0000e+00, -2.0200e+02],
        [ 3.0000e+00, -6.0000e+00,  3.0000e+00,  1.0100e+02],
        [ 1.0100e+02, -2.0200e+02,  1.0100e+02,  9.8030e+03]])


In [21]:
# Tanda "_" artinya operasi "inplace" ... ini penting untuk diingat untuk menekan memory. Terutama di GPU

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[ 1.,  0.,  1.,  1.],
        [-2., -2., -2., -2.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1., 99.]]) 

tensor([[  6.,   5.,   6.,   6.],
        [  3.,   3.,   3.,   3.],
        [  6.,   5.,   6.,   6.],
        [  6.,   5.,   6., 104.]])


In [22]:
# Tentu saja Tensor dapat diubah kembali kke numpy
# Coba sampaikan di kolom komentar, kira-kira kapan kita butuh hal ini?
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
# Tapi "reference to variable" seperti di adsp-01 tetap berlaku (pythonic)
# perubahan di t akan merubah n
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# <center><font color="blue"> Akhir Modul DL 02 - Pendahuluan PyTorch untuk Deep learning</font></center>

* Referensi: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
<hr />
<img alt="" src="images/meme-cartoon/meme tensors flow node to node.jpeg" style="height: 400px;"/>